### ISSUE TITLE
Unable to establish connection between two nodes

### ISSUE THREAD

**Issue by ronaldmannak** [ElementsProject/lightning#1798]
### Issue and Steps to Reproduce
I'm running two Lightning nodes with the same setup. I am unable to connect node 1 to node 2 and node 2 to node 1

```
$ lightning-cli connect 0271228bc352dc732012fd2e275a9c3cd39d05e03e398600502e74d9c03b14f45a@159.89.157.98

{ "code" : -1, "message" : "Connection establishment: Connection refused" }
```

```
lightning-cli connect 02060d0c8577cfc2a1962220a1cde4f623ca55ef80bd25e4be5a8b15fed78b11a3@178.62.237.239

{ "code" : -1, "message" : "Connection establishment: Connection refused" }
```

Both nodes are able to connect to most other nodes, but not each other.

### `getinfo` output

Node 1:
```
{
  "id": "02060d0c8577cfc2a1962220a1cde4f623ca55ef80bd25e4be5a8b15fed78b11a3",
  "port": 9735,
  "address": [
    {
      "type": "ipv4",
      "address": "178.62.237.239",
      "port": 9735
    }
  ],
  "binding": [
  ],
  "version": "",
  "blockheight": 534904,
  "network": "bitcoin"
}
```

Node 2:
```
{
  "id": "0271228bc352dc732012fd2e275a9c3cd39d05e03e398600502e74d9c03b14f45a",
  "port": 9735,
  "address": [
    {
      "type": "ipv4",
      "address": "159.89.157.98",
      "port": 9735
    }
  ],
  "binding": [
  ],
  "version": "",
  "blockheight": 534904,
  "network": "bitcoin"
}
```

**Comment by cdecker** [comment]
Neither of the nodes is reachable over the internet when I tried just now. This leads me to believe that they are either sitting behind a NAT, a firewall, or are not running. In case of a NAT (e.g., they are running on the home network of someone), the port 9735 needs to be forwarded to the machine running the nodes. In the case of a firewall you need to allow incoming connections on port 9735.

**Comment by ronaldmannak** [comment]
@cdecker You were right, I had blocked the 9735 port. I've opened up the ports now, but the issue persists.

```
To                         Action      From
--                         ------      ----
...
9735                       ALLOW       Anywhere
9735 (v6)                  ALLOW       Anywhere (v6)
9735                       ALLOW OUT   Anywhere
9735 (v6)                  ALLOW OUT   Anywhere (v6)
```

**Comment by cdecker** [comment]
Neither of the machines is reachable from my side of the Internet, are they currently running/behind NAT?

**Comment by jb55** [comment]
Try

    ss -plant | grep 9735

and make sure you see something like:

    LISTEN   0      5          *:9735         *:*

if you see this there's a good chance it's still a firewall issue.

I don't see the ports open from my side:

    nmap -PN -p 9735 178.62.237.239 159.89.157.98
    Starting Nmap 7.70 ( https://nmap.org ) at 2018-08-03 13:07 PDT
    Nmap scan report for 178.62.237.239
    Host is up (0.16s latency).

    PORT     STATE  SERVICE
    9735/tcp closed unknown

    Nmap scan report for 159.89.157.98
    Host is up (0.036s latency).

    PORT     STATE  SERVICE
    9735/tcp closed unknown

    Nmap done: 2 IP addresses (2 hosts up) scanned in 0.24 seconds

but I do see ssh ports open

**Comment by ronaldmannak** [comment]
Yeah, I don't see the port open on scanners I use. This is an odd issue, since both of my nodes able to connect to other nodes, so that suggests my nodes can at least send out data on port 9735.

Both bitcoind and lightningd are running in Docker containers, I'm running ufw (ufw status output in my previous comment). Not using NAT. Bitcoind has port 9735 mapped. This is kind of odd setup, I thought I would have to expose port 9735 on the Lightning node, but this is according to the documentation and tutorials I found online (hey, if you can't trust the internet, what can you trust?). Seriously though, what I can imagine is that documentation I found to install Lightning was out of date, and I need to close the 9735 port on the bitcoind container and open it on the lightningd container. Would that make sense?

```
$ ss -plant | grep 9735

LISTEN     0      128         :::9735                    :::*                   users:(("docker-proxy",pid=7358,fd=4))
```

```
$ docker ps
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS                                                                       NAMES
1d545c7f5683        elementsproject/lightningd   "/usr/bin/lightningd…"   4 minutes ago       Up 4 minutes                                                                                    lightning
f8c645312d94        dougvk/bitcoind:latest       "/entrypoint.sh bitc…"   2 weeks ago         Up 2 weeks          0.0.0.0:8333->8333/tcp, 8332/tcp, 18332-18333/tcp, 0.0.0.0:9735->9735/tcp   bitcoind
```

**Comment by ronaldmannak** [comment]
I believe the confusing part is that the nodes seem to work for fine in the sense that you are able to create and fund channels. This leads to a false sense of security. 

If the node wouldn't work at all, at least you'd have a signal that something is wrong. The only way to find out something is wrong now is to fire up a second node, or hope other people in the community will reach out to you if they are unable to connect to your node. 

Channels already show a status, so perhaps a feature where Lighting would check the setup would be useful. The status could for example be reported in `getinfo`.

**Comment by ronaldmannak** [comment]
@cdecker Yes, it seems that way, but I can't expose the port while using `-network container:bitcoind`. I tried to create a bridge, like `docker network create --driver bridge letwork` which does allow me to open ports on both containers, but then the two containers can't communicate with each other anymore. Error message:

```
Could not connect to bitcoind using bitcoin-cli. Is bitcoind running?
Make sure you have bitcoind running and that bitcoin-cli is able to connect to bitcoind.
You can verify that your Bitcoin Core installation is ready for use by running:
$ bitcoin-cli echo 'hello world'
```

I'm not a Docker expert, but the issue seems to be a Docker issue, not a C-Lightning issue perse. The sub-par quality of their documentation doesn't make it any easier.

**Comment by ronaldmannak** [comment]
I removed both containers and reinstalled bitcoind and C-Lightning using docker-compose. Here's my docker-compose.yml file, based on the yml file in this repo's readme:

```
version: "3"
services:
  bitcoind:
    image: nicolasdorier/docker-bitcoin:0.16.0
    environment:
      BITCOIN_EXTRA_ARGS: |
        testnet=0
        whitelist=0.0.0.0/0
        server=1
        rpcuser=rpcuser
        rpcpassword=rpcpass
    expose:
      - "8333"
    volumes:
      - "/scratch/bitcoin/mainnet/bitcoind:/data"

  clightning_bitcoin:
    image: elementsproject/lightningd
    command:
      - --bitcoin-rpcconnect=bitcoind
      - --bitcoin-rpcuser=rpcuser
      - --bitcoin-rpcpassword=rpcpass
      - --network=bitcoin
      - --alias=punchbeef2
      - --log-level=debug
    environment:
      EXPOSE_TCP: "true"
    expose:
      - "9735"
    volumes:
      - "/scratch/bitcoin/mainnet/clightning:/root/.lightning"
      - "/scratch/bitcoin/mainnet/bitcoind:/etc/bitcoin"
    links:
      - bitcoind
```

This time, the two containers can talk to each other and have the right ports for each container are set correctly: 

```
$ docker ps
CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS              PORTS                                             NAMES
dc162268983b        elementsproject/lightningd            "./entrypoint.sh --b…"   41 minutes ago      Up 41 minutes       9735/tcp                                          compose_clightning_bitcoin_1
77100530d9c9        nicolasdorier/docker-bitcoin:0.16.0   "/entrypoint.sh bitc…"   41 minutes ago      Up 41 minutes       8332-8333/tcp, 18332-18333/tcp, 18443-18444/tcp   compose_bitcoind_1
```

I've confirmed ufw is set up correctly:

```
$ ufw status
WARN: / is group writable!
Status: active

To                         Action      From
--                         ------      ----
22                         LIMIT       Anywhere
2375/tcp                   ALLOW       Anywhere
2376/tcp                   ALLOW       Anywhere
9735                       ALLOW       Anywhere
22 (v6)                    LIMIT       Anywhere (v6)
2375/tcp (v6)              ALLOW       Anywhere (v6)
2376/tcp (v6)              ALLOW       Anywhere (v6)
9735 (v6)                  ALLOW       Anywhere (v6)

9735                       ALLOW OUT   Anywhere
9735 (v6)                  ALLOW OUT   Anywhere (v6)
```

I'm able to connect successfully to a random node I found on 1ml.com:

```
lightning-cli connect 02d4121ac85eee4de78331f1be3988cbeff2eb28b1ca30d31b1da806f5d90c5fad@35.203.64.15:9735
{
  "id": "02d4121ac85eee4de78331f1be3988cbeff2eb28b1ca30d31b1da806f5d90c5fad"
}
```

So I'm able to exactly what I was able to do before when I installed the containers manually. So far so good.

Unfortunately, I'm still running into the same issue. When I try to connect from my other node, I still cannot connect:

```
$ lightning-cli connect 0271228bc352dc732012fd2e275a9c3cd39d05e03e398600502e74d9c03b14f45a@159.89.157.98
lightning-cli: Connecting to 'lightning-rpc': Connection refused
```

When I check on https://www.yougetsignal.com/tools/open-ports/ , the port is still closed. 

I'm lost. Perhaps it wasn't a Docker issue after all(?)

# Getinfo
```
lightning-cli getinfo
{
  "id": "0271228bc352dc732012fd2e275a9c3cd39d05e03e398600502e74d9c03b14f45a",
  "port": 9735,
  "address": [
    {
      "type": "ipv4",
      "address": "159.89.157.98",
      "port": 9735
    }
  ],
  "binding": [
  ],
  "version": "",
  "blockheight": 535571,
  "network": "bitcoin"
}
```

**Comment by cdecker** [comment]
`expose` doesn't really setup the port forwarding. I tested the following `docker-compose.yml` and it works for my external IP:

```
version: "3"
services:
  bitcoind:
    image: nicolasdorier/docker-bitcoin:0.16.0
    environment:
      BITCOIN_EXTRA_ARGS: |
        testnet=0
        whitelist=0.0.0.0/0
        server=1
        rpcuser=rpcuser
        rpcpassword=rpcpass
    expose:
      - "8333"
    volumes:
      - "/scratch/bitcoin/mainnet/bitcoind:/data"

  clightning_bitcoin:
    image: elementsproject/lightningd
    command:
      - --bitcoin-rpcconnect=bitcoind
      - --bitcoin-rpcuser=rpcuser
      - --bitcoin-rpcpassword=rpcpass
      - --network=bitcoin
      - --alias=punchbeef2
      - --log-level=debug
    environment:
      EXPOSE_TCP: "true"
    ports:
      - "0.0.0.0:9735:9735"
    volumes:
      - "/scratch/bitcoin/mainnet/clightning:/root/.lightning"
      - "/scratch/bitcoin/mainnet/bitcoind:/etc/bitcoin"
    links:
      - bitcoind
```

Hope that helps. In any case this is not really a c-lightning issue, but rather a docker networking issue. Closing.
