### ISSUE TITLE
Two nodes in the same machine - can't connect from one to another

### ISSUE THREAD

**Issue by sidaudhi** [ElementsProject/lightning#2337]
### Issue and Steps to Reproduce
I have two nodes running on ports 9735 and 9112 on the same DigitalOcean droplet. 

When I try to connect from one to the other:
`docker exec lightning lightning-cli connect 038de60a0cb43eea67e0bcb6e207daebad312a245cedd8b09deb2c5ba4bb19f601 138.68.231.196 9112`

i get the error: 
`{ "code" : -1, "message" : "138.68.231.196:9112: Cryptographic handshake: peer closed connection (wrong key?). " }`

Both my nodes are built out of image: elementsproject/lightningd and ports 9735 and 9112 are open through the DigitalOcean UFW firewall.

### `getinfo` output
Node 1:
```
{
  "id": "0230d70b0506aa447a1db407cc04e41448ab92bbd373f5c9a1029a40f357fcdcad",
  "alias": "LN.pay",
  "color": "20b0cf",
  "num_peers": 2,
  "num_pending_channels": 0,
  "num_active_channels": 1,
  "num_inactive_channels": 1,
  "address": [
    {
      "type": "ipv4",
      "address": "138.68.231.196",
      "port": 9735
    }
  ],
  "binding": [
  ],
  "version": "v0.6.3rc1-118-g0da4054",
  "blockheight": 562550,
  "network": "bitcoin",
  "msatoshi_fees_collected": 0
}
```
Node 2:
```
{
  "id": "038de60a0cb43eea67e0bcb6e207daebad312a245cedd8b09deb2c5ba4bb19f601",
  "alias": "ln.pay.2",
  "color": "20b0cf",
  "num_peers": 0,
  "num_pending_channels": 0,
  "num_active_channels": 0,
  "num_inactive_channels": 0,
  "address": [
    {
      "type": "ipv4",
      "address": "138.68.231.196",
      "port": 9112
    }
  ],
  "binding": [
  ],
  "version": "v0.6.3rc1-118-g0da4054",
  "blockheight": 562550,
  "network": "bitcoin",
  "msatoshi_fees_collected": 0
}
```
Docker compose setup:
```
clightning_bitcoin:
    image: elementsproject/lightningd
    container_name: lightning
    command:
      - --announce-addr=138.68.231.196:9735
    environment:
      EXPOSE_TCP: "true"
    expose:
      - "9735"
    ports:
      - "0.0.0.0:9735:9735"

clightning_02_bitcoin:
    image: elementsproject/lightningd
    container_name: lightning_02
    command:
      - --announce-addr=138.68.231.196:9112
    environment:
      EXPOSE_TCP: "true"
    expose:
      - "9735"
    ports:
      - "0.0.0.0:9112:9735"
```
