### ISSUE TITLE
Docker compose: /usr/bin/env: 'python3': No such file or directory

### ISSUE THREAD

**Issue by educob** [ElementsProject/lightning#3765]
Hi.

I have the following c-lightning service in a docker-compose.yml file:

```
  clightning_bitcoin:
    image: elementsproject/lightningd
    container_name: testnetln
    command:
      - --network=testnet
      - --bitcoin-rpcconnect=testnetnode
      - --bitcoin-rpcuser=xxx
      - --bitcoin-rpcpassword=yyy
      - --bind-addr=0.0.0.0:9901
      - --alias=bappTestnet
      - --log-level=debug
      - --plugin=/root/.lightning/ln_testnet.py

    environment:
      EXPOSE_TCP: "true"
    expose:
      - "9901"
    ports:
      - "0.0.0.0:9901:9901"
    volumes:
      - "/media/r2d2/ssd_2/testnet/ln:/root/.lightning"
      - "/media/r2d2/ssd_2/testnet/bitcoin:/etc/bitcoin"
    links:
      - testnetnode
```

As you can see I am running a python plugin: `/root/.lightning/ln_testnet.py`

When upping the docker-compose I get error:
` /usr/bin/env: 'python3': No such file or directory`

I have seen this kind of errors when running docker on windows because EOL but I am running on linux-mint 19.2

Thanks.

UPDATE: I think the problem is that there no python3 installed on the image.
I have open a bash and tried to run "apt-get install python3" but it doesn't find the package I can't figure it out why.
