### ISSUE TITLE
Funding Tx finalized for channel in AWAITING_UNILATERAL status

### ISSUE THREAD

**Issue by theRescuer** [ElementsProject/lightning#4512]
### Issue and Steps to Reproduce
I've executed a funding transactions to establish a channel with peer `0234227bdcd0361622f39447f961618480e7347ab1cfe6e74f561b976135343b31`
The transaction has remained "unconfirmed" in the mempool (due to low fee rates)for several days .
Today, eventually it went through.
In the meantime the request for channel moved to AWAITING_UNILATERAL state
```
state_changes:
          - timestamp: '2021-04-27T12:29:48.672Z'
            old_state: CHANNELD_AWAITING_LOCKIN
            new_state: AWAITING_UNILATERAL
            cause: protocol
            message: >-
              channeld: received ERROR channel
              ae169b356c7eeb905ea6b0d6e705be8626209e0aac5a315cb80400288d143098:
              funding failed due to internal error
        status:
          - 'AWAITING_UNILATERAL:Attempting to reconnect'
        in_payments_offered: 0
        in_msatoshi_offered: 0
        in_offered_msat: 0msat
        in_payments_fulfilled: 0
        in_msatoshi_fulfilled: 0
        in_fulfilled_msat: 0msat
        out_payments_offered: 0
        out_msatoshi_offered: 0
        out_offered_msat: 0msat
        out_payments_fulfilled: 0
        out_msatoshi_fulfilled: 0
        out_fulfilled_msat: 0msat
        htlcs: []
```

listpeers with debug parameter shows
```
log: >-
          Funding tx
          9830148d280004b85c315aac0a9e202686be05e7d6b0a65e90eb7e6c359b16ae
          confirmed, but peer disconnected
```

I do not understand why the request for closure was raised.
Any suggestion on how to get the funds back (even enforcing a real unilateral channel closure if no other option is available)

### `getinfo` output
```
id: 023808f558a644d786cb9071ea22f2afcd7329326170eded00dd2ce0b4e377ed2f
alias: ANGRYSOURCE
color: 023808
num_peers: 7
num_pending_channels: 0
num_active_channels: 5
num_inactive_channels: 0
address:
  - type: ipv4
    address: 51.68.5.193
    port: 9735
  - type: torv3
    address: y5osgenmyzhlohcnkbxl4swwhkrk4hbggrpgkvzyd5mj6ocgqoohqpqd.onion
    port: 9735
binding:
  - type: ipv4
    address: 0.0.0.0
    port: 9735
version: basedon-v0.9.3-1
blockheight: 682235
network: bitcoin
msatoshi_fees_collected: 5700
fees_collected_msat: 5700msat
lightning-dir: /root/.lightning/bitcoin
```
