### ISSUE TITLE
gRPC not included with official docker image

### ISSUE THREAD

**Issue by KayBeSee** [ElementsProject/lightning#5269]
### Issue and Steps to Reproduce
I am trying to setup c-lightning and communicate via GRPC commands but am unable to do so. It looks like the grpc plugin is not included with the [official docker image](https://hub.docker.com/r/elementsproject/lightningd).

I am using this docker-compose.yml file:
```
lightning:
    image: elementsproject/lightningd:latest
    command:
      - --bitcoin-rpcconnect=bitcoind
      - --bitcoin-rpcuser=someuser
      - --bitcoin-rpcpassword=avalidpassword
      - --network=regtest
      - --plugin-dir=/usr/libexec/c-lightning/plugins
      - --alias=myawesomenode
      - --log-level=debug
    volumes:
      - ./data/lightning:/root/.lightning
      - ./data/bitcoin:/root/.bitcoin
    ports:
      - "8001:8001"

  bitcoind:
    image: lncm/bitcoind:v22.0@sha256:37a1adb29b3abc9f972f0d981f45e41e5fca2e22816a023faa9fdc0084aa4507
    volumes:
      - ${PWD}/data/bitcoin:/data/.bitcoin
    restart: on-failure
    ports:
      - "18443:18443"
```

I run `docker-compose up` and the container starts up successfully.

I am able to run `docker exec -it CLIGHTNING_CONTAINER_ID bash` and get  into the container, but when I run `lightning-cli --network=regtest plugin list` while inside the container, I don't get the grpc plugin listed.

Here is the response from `lightning-cli --network=regtest plugin list`:

```
{
   "command": "list",
   "plugins": [
      {
         "name": "/usr/local/bin/../libexec/c-lightning/plugins/autoclean",
         "active": true
      },
      {
         "name": "/usr/local/bin/../libexec/c-lightning/plugins/bcli",
         "active": true
      },
      {
         "name": "/usr/local/bin/../libexec/c-lightning/plugins/funder",
         "active": true
      },
      {
         "name": "/usr/local/bin/../libexec/c-lightning/plugins/topology",
         "active": true
      },
      {
         "name": "/usr/local/bin/../libexec/c-lightning/plugins/keysend",
         "active": true
      },
      {
         "name": "/usr/local/bin/../libexec/c-lightning/plugins/offers",
         "active": true
      },
      {
         "name": "/usr/local/bin/../libexec/c-lightning/plugins/pay",
         "active": true
      },
      {
         "name": "/usr/local/bin/../libexec/c-lightning/plugins/txprepare",
         "active": true
      },
      {
         "name": "/usr/local/bin/../libexec/c-lightning/plugins/spenderp",
         "active": true
      }
   ]
}
```

When I add `- --grpc-port=8001` to the command in `docker-compose.yml` I get the following error before the container dies: `lightning_1  | /usr/local/bin/lightningd: --grpc-port=8001: unrecognized option`

Is there a way to enable the grpc plugin using the official docker image?
