### ISSUE TITLE
Can't start wss-proxy

### ISSUE THREAD

**Issue by Ks2wAu89jnEgCR0bGUAA** [ElementsProject/lightning#8360]
I added ''bind-addr=ws:...'' to my cln config and Upon startup the logs would show erros indicating python dependencies weren't installed so i installed websocket and pyln. The error seemed to go so I assumed the plugin started normally. Then I tried to setup cln-application but I keep getting websocket error and now after listing plugins I se that wss-proxy isnt even there.

Have I done something dumb or is there a way I can resolve this?

**Comment by ShahanaFarooqui** [comment]
Please verify your `bind-addr=ws:` and `wss-bind-addr` configurations as per the [official documentation](https://docs.corelightning.org/docs/wss-proxy#wss-proxy). For proper wss proxy functionality, ensure all three settings are correctly defined. 

For example:
```
bind-addr=ws:127.0.0.1:5011  
wss-bind-addr=127.0.0.1:5051  
wss-certs=/root/.lightning/bitcoin
```

setup will show up in `lsof -i | grep LISTEN` result as:

![Image](https://github.com/user-attachments/assets/61e7c4da-90ef-4a8f-9391-e56f9764b4ca)

 
Also, ensure that there is no `UNUSUAL` log entry related to `plugin-wss-proxy` in your CLN logs.

**Comment by Ks2wAu89jnEgCR0bGUAA** [comment]
Thank you so much, this worked :)

When im trying to start cln-application i get a ''WebSocket error: {}'' I have set the port using the env.sh and sourced it. The port i am using is the 2106 that i've put after bind-addr=ws: in the lightning config
 ```
export LIGHTNING_WEBSOCKET_PORT="2106"
```
I'm not sure why it's not working now, I have done lightning-cli plugin list and can verify wss-proxy is active at port 2106?

Here's my full lightning config and env.sh if that may provide some more useful context:
```
export BITCOIN_NETWORK="bitcoin"
export BITCOIN_NODE_IP="127.0.0.1"
export APP_PORT="2103"
export HIDDEN_SERVICE_URL="http://xyz.onion"
export APP_MODE="production"
export APP_PROTOCOL="http"
export DEVICE_DOMAIN_NAME="nodebox.local"
export LOCAL_HOST="http://""nodebox.local"
export APP_IP="127.0.0.1"
export LIGHTNING_IP="127.0.0.1"
export APP_CONFIG_DIR="/home/satoshi/cln-app"
export LIGHTNING_WEBSOCKET_PORT="2106"
export COMMANDO_CONFIG="/home/satoshi/cln-app/commando.config"
export SINGLE_SIGN_ON="false"
export LIGHTNING_PATH="/home/satoshi/.lightning"
echo "Local Environment Variables Set"
```
and
```
alias=xyz
rgb=000000
network=bitcoin

log-file=/home/satoshi/.lightning/cln.log
log-level=info

proxy=127.0.0.1:9050
bind-addr=ws:0.0.0.0:2106
wss-bind-addr=0.0.0.0:2107
wss-certs=/home/satoshi/.lightning/bitcoin
bind-addr=0.0.0.0:9738
addr=statictor:127.0.0.1:9051/torport=9738
always-use-proxy=true

bitcoin-cli=/usr/local/bin/bitcoin-cli
bitcoin-datadir=/home/satoshi/.bitcoin
bitcoin-rpcuser=rdtyrhjdr
bitcoin-rpcpassword=dyhdryddjy

bitcoin-rpcconnect=127.0.0.1
bitcoin-rpcport=8332

clnrest-port=2010
clnrest-protocol=https
clnrest-host=0.0.0.0
clnrest-cors-origins=*

experimental-offers

grpc-port=2108
```

**Comment by ShahanaFarooqui** [comment]
Currently, cln-application only supports WebSocket (ws) communication via Commando (lnmessage). This limitation will be addressed in the upcoming v0.0.8 release, as I have just implemented this enhancement in PR [#112](https://github.com/ElementsProject/cln-application/pull/112).

While your node's WSS-proxy configuration appears correct, cln-application does not currently utilise WSS connections in its implementation. Your environment configuration otherwise looks good to me.

I would suggested to troubleshoot further by:
- Temporarily disabling Tor setup to isolate the issue
- Verifying your port forwarding configuration

**Comment by Ks2wAu89jnEgCR0bGUAA** [comment]
Thank you for the help  <3.

Its worth mentioning that after a bit of tinkering I was able to use cln-application with docker compose, here is the config I used:
```
version: "3.7"

services:
  cln-gui:
    image: ghcr.io/elementsproject/cln-application:0.0.7
    command: npm run start
    restart: always
    network_mode: host
    ports:
      - 127.0.0.1:2103:2103
    volumes:
      - /home/satoshi/cln-gui/data/app:/conf
      - /home/satoshi/.lightning:/cln
      - /home/satoshi/.lightning/bitcoin:/cert
      - /home/satoshi/cln-app/.commando:/commando/commando-conf
    environment:
      SINGLE_SIGN_ON: "false"
      APP_CORE_LIGHTNING_IP: "172.17.0.1"
      LIGHTNING_PATH: "/cln"
      BITCOIN_NETWORK: "bitcoin"
      APP_CORE_LIGHTNING_PORT: "2103"
      APP_CORE_LIGHTNING_BITCOIN_NETWORK: "bitcoin"
      APP_CORE_LIGHTNING_DAEMON_IP: "172.17.0.1"
      APP_CORE_LIGHTNING_DAEMON_GRPC_PORT: "2108"
      APP_CORE_LIGHTNING_WEBSOCKET_PORT: "2106"
      APP_CORE_LIGHTNING_REST_PORT: "2010"
      APP_CORE_LIGHTNING_REST_CERT_DIR: "/cert"
      APP_CORE_LIGHTNING_REST_HIDDEN_SERVICE: "xyz.onion"
      CORE_LIGHTNING_PATH: "/cln"
      COMMANDO_CONFIG: "/commando/commando-conf"
      APP_CONFIG_DIR: "/conf"
      APP_MODE: "production"
      DEVICE_DOMAIN_NAME: "nodebox.local"
      LOCAL_HOST: "http://nodebox.local"
      CA_CERT: "/cln/bitcoin/ca.pem"
      CLIENT_KEY: "/cln/bitcoin/client-key.pem"
      CLIENT_CERT: "/cln/bitcoin/client.pem"
```

I only had a minor issue using it like this, when I deposited a small amount of test funds on chain (twice just to test) no transaction popped up as unconfirmed (in cln-application, zeus or RTL). But after the txn confirmed the funds popped up instantly. Is this a quirk of CLN or is there some sort of config I should add to allow the unconfirmed transactions to pop up.

[Also when withdrawing the OC funds out of cln the txn does not show as unconfirmed]

Just wanted to say thanks again for maintaining this great software and answering noob questions like mine :)
